package com.gustavo.vista;

import com.gustavo.modelo.PersonaBBDD;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Font;
import javax.swing.JOptionPane;

public class Contacto extends javax.swing.JPanel {

    private PersonaBBDD personaBBDD;

    /**
     * Creates new form Anfitrion
     */
    public Contacto() {
        initComponents();
        tablaPersonas.getTableHeader().setFont(new Font("Roboto", Font.BOLD, 12));
        tablaPersonas.getTableHeader().setOpaque(false);
        tablaPersonas.getTableHeader().setBackground(new Color(32, 136, 203));
        tablaPersonas.getTableHeader().setForeground(new Color(0, 0, 0));
        actualizarTabla();
    }

    private void actualizarTabla() {
        personaBBDD = new PersonaBBDD();

        tablaPersonas.setModel(personaBBDD.llenarTablaPersonas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lblLituloAnfitrion = new javax.swing.JLabel();
        lblNombreApellido = new javax.swing.JLabel();
        txtNombreApellido = new javax.swing.JTextField();
        lineaNombreApellido = new javax.swing.JSeparator();
        btnGuardarPersona = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonas = new javax.swing.JTable();
        txtBuscarPersona = new javax.swing.JTextField();
        lineaNombreApellido1 = new javax.swing.JSeparator();
        btnBuscarPersona = new javax.swing.JLabel();
        btnBorrarPersona = new javax.swing.JLabel();
        btnEditarPersona = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));

        lblLituloAnfitrion.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblLituloAnfitrion.setForeground(new java.awt.Color(0, 0, 0));
        lblLituloAnfitrion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLituloAnfitrion.setText("Contactos");

        lblNombreApellido.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblNombreApellido.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreApellido.setText("Nombre y apellido");

        txtNombreApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreApellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNombreApellido.setForeground(new java.awt.Color(204, 204, 204));
        txtNombreApellido.setText("Ingresar nombre y apellido");
        txtNombreApellido.setBorder(null);
        txtNombreApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreApellidoMousePressed(evt);
            }
        });

        btnGuardarPersona.setBackground(new java.awt.Color(0, 153, 255));
        btnGuardarPersona.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnGuardarPersona.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarPersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGuardarPersona.setText("Guardar");
        btnGuardarPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarPersona.setOpaque(true);
        btnGuardarPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarPersonaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarPersonaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarPersonaMouseExited(evt);
            }
        });

        tablaPersonas.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPersonas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tablaPersonas);

        txtBuscarPersona.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscarPersona.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtBuscarPersona.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscarPersona.setText("Buscar persona por nombre y apellido");
        txtBuscarPersona.setBorder(null);
        txtBuscarPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtBuscarPersonaMousePressed(evt);
            }
        });

        btnBuscarPersona.setBackground(new java.awt.Color(0, 153, 255));
        btnBuscarPersona.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnBuscarPersona.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarPersona.setText("Buscar");
        btnBuscarPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarPersona.setOpaque(true);
        btnBuscarPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarPersonaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarPersonaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarPersonaMouseExited(evt);
            }
        });

        btnBorrarPersona.setBackground(new java.awt.Color(0, 153, 255));
        btnBorrarPersona.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnBorrarPersona.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarPersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBorrarPersona.setText("Borrar");
        btnBorrarPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrarPersona.setOpaque(true);
        btnBorrarPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarPersonaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBorrarPersonaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBorrarPersonaMouseExited(evt);
            }
        });

        btnEditarPersona.setBackground(new java.awt.Color(0, 153, 255));
        btnEditarPersona.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnEditarPersona.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarPersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEditarPersona.setText("Editar");
        btnEditarPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarPersona.setOpaque(true);
        btnEditarPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarPersonaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarPersonaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarPersonaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(lblLituloAnfitrion, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreApellido)
                    .addComponent(lineaNombreApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addComponent(btnGuardarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lineaNombreApellido1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscarPersona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(btnEditarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnBorrarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(lblLituloAnfitrion, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineaNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(txtBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineaNombreApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarPersonaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarPersonaMouseEntered
        btnGuardarPersona.setBackground(new Color(9, 146, 247));
    }//GEN-LAST:event_btnGuardarPersonaMouseEntered

    private void btnGuardarPersonaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarPersonaMouseExited
        btnGuardarPersona.setBackground(new Color(0, 153, 255));
    }//GEN-LAST:event_btnGuardarPersonaMouseExited

    private void txtNombreApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreApellidoMousePressed
        if (txtNombreApellido.getText().equals("Ingresar nombre y apellido")) {
            txtNombreApellido.setText("");
            txtNombreApellido.setForeground(Color.black);
        }

        if (txtBuscarPersona.getText().equals("")) {
            txtBuscarPersona.setForeground(Color.lightGray);
            txtBuscarPersona.setText("Buscar persona por nombre y apellido");
        }
    }//GEN-LAST:event_txtNombreApellidoMousePressed

    private void btnGuardarPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarPersonaMouseClicked
        PersonaBBDD personaBBDD;
        if (txtNombreApellido.getText().equals("") || txtNombreApellido.getText().equals("Ingresar nombre y apellido")) {
            JOptionPane.showMessageDialog(null, "Complete el campo Nombre y apellido. ", "Advertencia", JOptionPane.WARNING_MESSAGE);

        } else {
            personaBBDD = new PersonaBBDD();
            personaBBDD.guardarPersona(txtNombreApellido.getText());
            actualizarTabla();
            JOptionPane.showMessageDialog(null, "Nombre y apellido guardado correctamente. " + txtNombreApellido.getText(), "Mensaje de confirmación", JOptionPane.INFORMATION_MESSAGE);

        }


    }//GEN-LAST:event_btnGuardarPersonaMouseClicked

    private void txtBuscarPersonaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarPersonaMousePressed

        if (txtBuscarPersona.getText().equals("Buscar persona por nombre y apellido")) {
            txtBuscarPersona.setText("");
            txtBuscarPersona.setForeground(Color.black);
        }

        if (txtNombreApellido.getText().equals("")) {
            txtNombreApellido.setForeground(Color.lightGray);
            txtNombreApellido.setText("Ingresar nombre y apellido");
        }
    }//GEN-LAST:event_txtBuscarPersonaMousePressed

    private void btnBuscarPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPersonaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPersonaMouseClicked

    private void btnBuscarPersonaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPersonaMouseEntered
        btnBuscarPersona.setBackground(new Color(9, 146, 247));
    }//GEN-LAST:event_btnBuscarPersonaMouseEntered

    private void btnBuscarPersonaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPersonaMouseExited
        btnBuscarPersona.setBackground(new Color(0, 153, 255));
    }//GEN-LAST:event_btnBuscarPersonaMouseExited

    private void btnBorrarPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarPersonaMouseClicked
        int filaSeleccionada = tablaPersonas.getSelectedRow();
        if (filaSeleccionada >= 0) {
            int numColumnas = tablaPersonas.getColumnCount();
//            for (int columna = 0; columna < numColumnas; columna++) {
//                Object valorCelda = tablaPersonas.getValueAt(filaSeleccionada, columna);
//                System.out.println("Columna " + columna + ": " + valorCelda);
//            }

            Object valorCelda = tablaPersonas.getValueAt(filaSeleccionada, 0);
            personaBBDD.eliminarPersona((int) valorCelda);
            actualizarTabla();
            JOptionPane.showMessageDialog(null, "Borrado correcto.", "Información", JOptionPane.INFORMATION_MESSAGE);

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una persona.", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }

    }//GEN-LAST:event_btnBorrarPersonaMouseClicked

    private void btnBorrarPersonaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarPersonaMouseEntered
        btnBorrarPersona.setBackground(new Color(9, 146, 247));
    }//GEN-LAST:event_btnBorrarPersonaMouseEntered

    private void btnBorrarPersonaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarPersonaMouseExited
        btnBorrarPersona.setBackground(new Color(0, 153, 255));
    }//GEN-LAST:event_btnBorrarPersonaMouseExited

    private void btnEditarPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarPersonaMouseClicked
        Prueba pr = new Prueba(10, "Gustavo silva artaza");
        pr.setSize(550, 490);
        pr.setLocation(0, 0);
        bg.removeAll();

        // Obtener el contenedor principal y llamar a cambiarPanel en él.
        Container container = getParent();
        if (container instanceof CambiarPanelListener) {
            ((CambiarPanelListener) container).cambiarPanel(pr);
        }

//        bg.add(pr, BorderLayout.CENTER);
        bg.revalidate();
        bg.repaint();
    }//GEN-LAST:event_btnEditarPersonaMouseClicked

    private void btnEditarPersonaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarPersonaMouseEntered
        btnEditarPersona.setBackground(new Color(9, 146, 247));
    }//GEN-LAST:event_btnEditarPersonaMouseEntered

    private void btnEditarPersonaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarPersonaMouseExited
        btnEditarPersona.setBackground(new Color(0, 153, 255));
    }//GEN-LAST:event_btnEditarPersonaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btnBorrarPersona;
    private javax.swing.JLabel btnBuscarPersona;
    private javax.swing.JLabel btnEditarPersona;
    private javax.swing.JLabel btnGuardarPersona;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLituloAnfitrion;
    private javax.swing.JLabel lblNombreApellido;
    private javax.swing.JSeparator lineaNombreApellido;
    private javax.swing.JSeparator lineaNombreApellido1;
    private javax.swing.JTable tablaPersonas;
    private javax.swing.JTextField txtBuscarPersona;
    private javax.swing.JTextField txtNombreApellido;
    // End of variables declaration//GEN-END:variables
}
