/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practicas;

import java.sql.*;

/**
 *
 * @author gustavo
 */
public class AplicacionConsulta extends javax.swing.JFrame {

    /**
     * Creates new form AplicacionConsulta
     */
    public AplicacionConsulta() {
        initComponents();

        try {
            miConexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/prueba", "root", "");

            Statement sentencia = miConexion.createStatement();
            //Carga combobox Ocupacion
            String consulta = "SELECT DISTINCTROW ocupacion FROM personas";

            ResultSet miResultset = sentencia.executeQuery(consulta);

            cbOcupacion.addItem("Todos");

            while (miResultset.next()) {
                cbOcupacion.addItem(miResultset.getString(1));

            }

            //Carga combobox pais
            consulta = "SELECT DISTINCTROW pais FROM personas";

            miResultset = sentencia.executeQuery(consulta);

            cbPais.addItem("Todos");

            while (miResultset.next()) {
                cbPais.addItem(miResultset.getString(1));

            }

            miResultset.close();

        } catch (Exception e) {
            System.out.println("NO SE CONECTA");
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbOcupacion = new javax.swing.JComboBox<>();
        cbPais = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResultado = new javax.swing.JTextArea();
        btnConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.add(cbOcupacion);

        jPanel1.add(cbPais);

        jPanel2.setLayout(new java.awt.BorderLayout());

        txtAreaResultado.setColumns(20);
        txtAreaResultado.setRows(5);
        jScrollPane1.setViewportView(txtAreaResultado);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnConsulta.setText("Consulta");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        jPanel2.add(btnConsulta, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        // TODO add your handling code here:
        ejecutarConsulta();
    }//GEN-LAST:event_btnConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicacionConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicacionConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicacionConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicacionConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplicacionConsulta().setVisible(true);
            }
        });
    }

    private void ejecutarConsulta() {
        txtAreaResultado.setText("");
        ResultSet rs = null;

        try {

            String ocupacion = (String) cbOcupacion.getSelectedItem();
            String pais = (String) cbPais.getSelectedItem();

            if (!ocupacion.equals("Todos") && pais.equals("Todos")) {

                enviaConsultaOcupacion = miConexion.prepareStatement(consultaOcupacion);
                enviaConsultaOcupacion.setString(1, ocupacion);
                rs = enviaConsultaOcupacion.executeQuery();

            } else if (ocupacion.equals("Todos") && !pais.equals("Todos")) {
                enviaConsultaOcupacion = miConexion.prepareStatement(consultaPais);
                enviaConsultaOcupacion.setString(1, pais);
                rs = enviaConsultaOcupacion.executeQuery();
            } else if (!ocupacion.equals("Todos") && !pais.equals("Todos")) {
                enviaConsultaOcupacion = miConexion.prepareStatement(consultaMultiplePaisOcupacion);
                enviaConsultaOcupacion.setString(1, ocupacion);
                enviaConsultaOcupacion.setString(2, pais);
                rs = enviaConsultaOcupacion.executeQuery();
            } else if (ocupacion.equals("Todos") && pais.equals("Todos")) {
                enviaConsultaOcupacion = miConexion.prepareStatement(consultaTodasLasPersonas);
                rs = enviaConsultaOcupacion.executeQuery();
            }

            while (rs.next()) {
                txtAreaResultado.append("Id: " + rs.getInt("id") + "\n");
                txtAreaResultado.append("Nombre: " + rs.getString("nombre") + "\n");
                txtAreaResultado.append("Edad: " + rs.getInt("edad") + "\n");
                txtAreaResultado.append("Ocupacion: " + rs.getString("ocupacion") + "\n");
                txtAreaResultado.append("Pais: " + rs.getString("pais") + "\n");
                txtAreaResultado.append("\n\n");

            }

            rs.close();

        } catch (Exception e) {
            System.out.println("NO SE CONECTA");
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsulta;
    private javax.swing.JComboBox<String> cbOcupacion;
    private javax.swing.JComboBox<String> cbPais;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaResultado;
    // End of variables declaration//GEN-END:variables

    private Connection miConexion;
    private PreparedStatement enviaConsultaOcupacion;
    private final String consultaOcupacion = "SELECT * FROM personas WHERE ocupacion=?";
    private final String consultaPais = "SELECT * FROM personas WHERE pais=?";
    private final String consultaTodasLasPersonas = "SELECT * FROM personas";
    private final String consultaMultiplePaisOcupacion = "SELECT * FROM personas WHERE ocupacion=? AND pais=?";

}
